In [1]:
import pandas as pd
#Step 1
#1.1
df = pd.read_table('RiskComplete.txt')

In [2]:
#Step 2
#2.1
df = df.drop_duplicates()

In [3]:
#2.2
df = df.drop(['ID'], axis = 1)
df

,AGE,INCOME,GENDER,MARITAL,NUMKIDS,NUMCARDS,HOWPAID,MORTGAGE,STORECAR,LOANS,VALUE
0,44,59944.0,m,married,1,2.0,monthly,y,2,0.0,strong profit
1,35,59692.0,m,married,1,1.0,monthly,y,1,0.0,bad loss
2,34,59463.0,m,married,0,2.0,monthly,y,1,1.0,bad loss
3,39,59393.0,f,married,0,2.0,monthly,y,1,0.0,strong profit
4,42,59201.0,m,married,0,1.0,monthly,y,2,0.0,strong profit
...,...,...,...,...,...,...,...,...,...,...,...
4121,21,15058.0,f,married,1,1.0,monthly,y,1,1.0,weak profit
4122,36,15054.0,m,married,2,2.0,monthly,y,2,2.0,weak profit
4123,41,15046.0,m,divsepwid,3,6.0,weekly,n,5,2.0,bad loss
4124,25,15020.0,f,married,2,0.0,weekly,y,1,1.0,weak profit
4125,50,15005.0,unknown,divsepwid,2,6.0,weekly,y,5,3.0,weak profit

In [4]:
#2.3
missing = df.isnull().sum()

In [5]:
#Question 1
print('Missing:\n', missing)
df['INCOME'] = df['INCOME'].fillna(round(df['INCOME'].mean()),)
df['GENDER'] = df['GENDER'].fillna(df['GENDER'].mode()[0])
df['NUMCARDS'] = df['NUMCARDS'].fillna(round(df['NUMCARDS'].mean()))
df['LOANS'] = df['LOANS'].fillna(round(df['LOANS'].mean()))
print('\nMissing values replaced:\n',df.isnull().sum())

Missing:
 AGE         0
INCOME      3
GENDER      4
MARITAL     0
NUMKIDS     0
NUMCARDS    4
HOWPAID     0
MORTGAGE    0
STORECAR    0
LOANS       5
VALUE       0
dtype: int64

Missing values replaced:
 AGE         0
INCOME      0
GENDER      0
MARITAL     0
NUMKIDS     0
NUMCARDS    0
HOWPAID     0
MORTGAGE    0
STORECAR    0
LOANS       0
VALUE       0
dtype: int64

In [9]:
#Question 2
print('Loan Average:',round((df['LOANS']).mean(),4))

Loan Average: 1.3758

In [12]:
#2.4
import numpy as np
df = df.replace('unknown', np.nan)
df = df.dropna()

In [13]:
#Question 3
print(df.shape[0])

4100

In [14]:
#Step 3
#Question 4
print('Ratio of females:',round((df['GENDER'] == 'f').mean(),4))

Ratio of females: 0.5049

In [16]:
#Question 5
print(df['VALUE'].value_counts())

VALUE
weak profit      2396
bad loss          901
strong profit     803
Name: count, dtype: int64

In [17]:
#Step 4
#4.1
df['VALUE'] = df['VALUE'].replace({'strong profit' : 'profit', 'weak profit':'profit', 'bad loss': 'loss'})

In [18]:
#Question 6
print(df['VALUE'].value_counts())

VALUE
profit    3199
loss       901
Name: count, dtype: int64

In [19]:
#4.2
inputs = ['GENDER', 'MARITAL', 'HOWPAID', 'MORTGAGE']
df = pd.get_dummies(df, columns=inputs, drop_first = True, dtype = int)
df['VALUE'] = df['VALUE'].replace({'profit':1, 'loss':0})
print(df['VALUE'].value_counts())

VALUE
1    3199
0     901
Name: count, dtype: int64

/var/folders/ch/p9c9jrhx04xdqhx1ng6_bgnh0000gn/T/ipykernel_51267/3688050548.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['VALUE'] = df['VALUE'].replace({'profit':1, 'loss':0})

In [20]:
#4.3
from sklearn.preprocessing import StandardScaler, MinMaxScaler
stscaler = StandardScaler()
standardized = ['AGE', 'INCOME']
df[standardized] = stscaler.fit_transform(df[standardized])
mmScaler = MinMaxScaler()
normalized = ['NUMKIDS','NUMCARDS','STORECAR','LOANS']
df[normalized] = mmScaler.fit_transform(df[normalized])

In [21]:
#Question 7
print('Standardized INCOME mean:',round(df['INCOME'].mean(),4))
print('Normalized NUMCARDS mean:',round(df['NUMCARDS'].mean(),4))

Standardized INCOME mean: 0.0
Normalized NUMCARDS mean: 0.4049

In [22]:
#Step 5
#5.1
x = df.drop('VALUE', axis = 1)
y = df['VALUE']

display(x.head(10))
display(y.head(10))

,AGE,INCOME,NUMKIDS,NUMCARDS,STORECAR,LOANS,GENDER_m,MARITAL_married,MARITAL_single,HOWPAID_weekly,MORTGAGE_y
0,1.232932,3.913128,0.25,0.333333,0.4,0.000000,1,1,0,0,1
1,0.321552,3.884416,0.25,0.166667,0.2,0.000000,1,1,0,0,1
2,0.220287,3.858324,0.00,0.333333,0.2,0.333333,1,1,0,0,1
3,0.726609,3.850348,0.00,0.333333,0.2,0.000000,0,1,0,0,1
4,1.030403,3.828472,0.00,0.166667,0.4,0.000000,1,1,0,0,1
5,-0.083506,3.827561,0.25,0.333333,0.2,0.333333,0,1,0,0,1
6,-0.387299,3.825966,0.25,0.166667,0.4,0.333333,1,1,0,0,1
7,-0.184771,3.809673,0.25,0.166667,0.4,0.333333,1,1,0,0,1
8,0.625345,3.795772,0.00,0.166667,0.2,0.333333,1,1,0,0,1
9,0.422816,3.791670,0.25,0.166667,0.2,0.000000,0,1,0,0,1

0    1
1    0
2    0
3    1
4    1
5    1
6    0
7    1
8    1
9    1
Name: VALUE, dtype: int64

In [23]:
#5.2
from sklearn.neural_network import MLPClassifier
features = x.shape[1]
modelNN = MLPClassifier(hidden_layer_sizes=(features,features,features),activation='logistic',solver='sgd',learning_rate_init=0.3,random_state = 1, shuffle=False)

In [24]:
#5.3
import time
start_time = time.time()
modelNN.fit(x,y)
end_time = time.time()

In [25]:
#Question 9
print('Model trained in', round(end_time - start_time, 2), 'seconds')

Model trained in 0.29 seconds

In [27]:
#Question 10
print('Total layers in model:', modelNN.n_layers_)
print('Number of output nodes:', modelNN.n_outputs_)
weight = modelNN.coefs_[0][9][0]
print('The weight between the 10th input and the 1st neuron of the first hidden layer is',weight)

Total layers in model: 5
Number of output nodes: 1
The weight between the 10th input and the 1st neuron of the first hidden layer is 0.34730373943564047

In [28]:
#Question 11
modelNN2 = MLPClassifier(hidden_layer_sizes=(500,500,500),activation='logistic',solver='sgd',learning_rate_init=0.3,random_state = 1, shuffle=False)
start_time = time.time()
modelNN2.fit(x,y)
end_time = time.time()
print('Model trained in', round(end_time - start_time, 2), 'seconds')
# Since the model went from 10 to 500 neurons per layer, it took much longer to train. Even with putting 500 neurons over three layers 
# on a dataset of around 4,100 rows, this neural network has more parameters than necessary.
# This could lead to overfitting within the model where it is now memorizing noise in the training set and is 
# less likely to generalize patterns.

Model trained in 7.08 seconds